# theme.toml template for a Hugo theme

name = "Affordable E-Commerce Theme"
license = "Creative Commons — Attribution 3.0 Unported — CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "An Affordable E-commerce theme powered by hugo"
homepage = "https://goldcoders.online"
tags = ["Ecommerce", "bootstrap", "blog", "contact", "responsive", "gethugothemes", "clean" , "Single Product", "Minimal", "light", "google analytics", "disqus", "mobile", "fast", "customizable", "white", "flex", "pages", "hugo themes", "hugo templates", "netlify", "Themefisher"]
features = ["Ecommerce", "responsive", "bootstrap-4"]
min_version = "0.58.0"

[author]
  name = "Goldcoders"
  homepage = "https://goldcoders.online"

