---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: CMS
- type: directory
  path: exampleSite/content/products
  label: Products
  create: all
  match: "**/*"
  exclude: "**index**"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
  exclude: "**index**"
- type: document
  path: exampleSite/data/faq.yml
  label: FAQ
- type: document
  path: exampleSite/content/terms-conditions/_index.md
  label: TOS
- type: heading
  label: Configurations
- type: document
  path: exampleSite/config.toml
  label: Web
- type: document
  path: exampleSite/data/homepage.yml
  label: Home
- type: document
  path: exampleSite/data/contact.yml
  label: Contact
- type: document
  path: exampleSite/data/snipcart.yml
  label: Snipcart
- type: document
  path: exampleSite/data/rating.yml
  label: Ratings
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
