baseURL = "https://shop.goldcoders.online"
disqusShortname = "goldcoders"
languageCode = "en-us"
paginate = 10
summaryLength = "20"
theme = "hargo"
title = "ECOM | Affordable E-commerce Site"
[[menu.footer]]
URL = "products"
name = "Products"
weight = 1
[[menu.footer]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.footer]]
URL = "faq"
name = "FAQ"
weight = 3
[[menu.footer]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 4
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "products"
name = "Products"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
author = "John Doe"
copyright = "| Copyright &copy; 2020 [Affordable Ecom](https://shop.goldcoders.online) All Rights Reserved |"
description = "Affordable Ecommerce Site"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/ecom-logo.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "ffc5ae4368e79c7fb3038908e56b93c8"
websiteID = "451186"
[params.snipcart]
apikey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
locale = "en"
poweredby = "goldcoders"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
