---
label: products
hide_body: false
fields:
- name: productID
  type: text
  config:
    required: false
  label: productID
  description: product id
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- name: shortdescription
  type: text
  config:
    required: false
  label: shortdescription
  description: short description
- name: price
  type: text
  config:
    required: false
  label: price
- name: priceBefore
  type: text
  config:
    required: false
  label: pricebefore
- name: type
  type: text
  config:
    required: false
  label: type
  default: products
  hidden: true
- name: og_type
  type: text
  config:
    required: false
  label: Og Type
  hidden: true
  default: og:product
- name: images
  type: image_gallery
  config: {}
  label: Images
