---
label: products
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- name: price
  type: text
  config:
    required: false
  label: price
- name: priceBefore
  type: text
  config:
    required: false
  label: pricebefore
- name: shortdescription
  type: text
  config:
    required: false
  label: shortdescription
  description: short description
- name: productID
  type: text
  config:
    required: false
  label: productID
  description: product id
- name: type
  type: text
  config:
    required: false
  label: type
  default: products
- name: images
  type: field_group_list
  fields:
  - name: image
    type: text
    config:
      required: false
    label: image
  config:
    min: 
    max: 
    labelField: 
  label: images
- name: og_type
  type: text
  config:
    required: false
  label: Og Type
  hidden: true
  default: og:product
- name: uploads
  type: image_gallery
  config: {}
  label: uploads
